bearer_token: <bearer_token>

timeline:
  # either provide username or userid
  user_id:
  username: nytimes
  tweet_fields: [ 'attachments', 'author_id', 'context_annotations', 'conversation_id',
                  'created_at', 'entities', 'geo',
                  'id', 'in_reply_to_user_id', 'lang', 'public_metrics',
                  'possibly_sensitive', 'referenced_tweets', 'reply_settings',
                  'source', 'text', 'withheld' ]
  # Output File Name
  output_file: test.json

  # format :: '2020-08-01T00:00:00Z'
  # start_time: 
  # end_time:
